apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

patches:
- patch: |-
    - op: replace
      path: /metadata/annotations/app.kubernetes.io~git-commit
      value: a1b2c3d4
  target:
    kind: Application
    name: prod-first-app

