apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    my-customize-field: "helloworld"
  name: second-nginx
spec:
  selector:
    matchLabels:
      run: second-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: second-nginx
    spec:
      containers:
      - name: second-nginx
        image: nginx:1.26.1
        ports:
        - containerPort: 80