apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: production-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Hironex-me/k8s-cookbook.git
        revision: main
        directories:
          # Add your project path
          - path: test.app
          - path: second-app
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: 'prod-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Hironex-me/k8s-cookbook.git
        targetRevision: HEAD
        path: '{{path}}/production'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'production'
      syncPolicy:
        automated: {}
